# Site settings
title: Occasionally Consistent
header-img: img/home-bg.jpg
email:
copyright_name: Michael Borisov
description: "Michael Borisov - software engineering blog - CQRS, DDD, TDD, BDD, micro services, event store, event driven architecture."
baseurl: ""
url: "https://corker.github.io"
twitter_username: fkem
github_username:  corker
facebook_username:  bmborisov
email_username:

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-92703902-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
